#!/bin/bash                                                                                                           

declare -A m

read_matrix() {
    local i=0
    local line
    local j
    
    read rows
    read cols
    while read -r line; do
        j=0
        
        for v in `echo $line`; do
            m[$i,$j]="$v"
            j=$((j+1))
        done
        i=$((i+1))
    done
}

read_matrix < matrix.txt

echo ${m[1,2]}
